### ISSUE TITLE
More documentation requested

### ISSUE THREAD

**Issue by olegstepura** [schmittjoh/metadata#1]
Hi!

From documentation it's not so clear how this library can be used. Can you please update the readme with more information on what this library is targeted to and some more verbose usage examples maybe.

As far as I can see it requires external annotation/xml/yaml/whatsoever reader adapter to get the metadata and those readers must implement some interface which make it necessary to implement it again for each use case but not use the existing Doctrine readers for example.

Does the lib provide the ability to use extra annotations which Doctrine Common's reader does not allow?
Does it cache the metadata information by default and what configuration it requires to make caching work.

It would be nice to have the annotated class as an example together with simple howto work with with it and description on the abstraction layers that this lib provides.

Thanks!

**Comment by Arkemlar** [comment]
+1 for requesting more documentation. It is not intuitive/obvious how to use the library.
