### ISSUE TITLE
 `jms/metadata 2.6.0` seems to be incompatible with `jms/serializer 3.15.0`

### ISSUE THREAD

**Issue by bobvandevijver** [schmittjoh/metadata#108]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | yes
| RFC?             | no

## Steps required to reproduce the problem

1. Use  `jms/metadata 2.6.0` with `jms/serializer 3.15.0`,
2. Deserialize an annotated object

Note that on the first request it works fine, but it breaks on the second request indicating it is a cache problem. Looking at what happens, it looks like the `PropertyMetadata` is used in the serializer, which has indeed received a BC breaking change looking at the [upgrading docs](https://github.com/schmittjoh/metadata/compare/2.5.2...2.6.0#diff-f411a5009131db5a6c7242b49ca78488f2d274ef9e5e5f4de9262a42108a5386) (not sure why it mentions from 2.0 to 2.3 though).

I believe 2.6 should have been released as a 3.0 version, indicating this major BC break for all consumers using the `PropertyMetadata`, or maybe the intended BC compatibility layer isn't working as expected?

## Expected Result

* Correct retrieval of class metadata

## Actual Result

* The meaningful properties of the metadata are all `null`.

**Comment by bobvandevijver** [comment]
[vich/uploader-bundle](https://github.com/dustin10/VichUploaderBundle) is also broken with version 2.6.0 of this library.

**Comment by goetas** [comment]
https://github.com/schmittjoh/metadata/pull/109 should fix it. Could you please try it?

**Comment by goetas** [comment]
fixed by https://github.com/schmittjoh/metadata/pull/109
