### ISSUE TITLE
Big performance hit when upgrading from 1.4.2 to 1.5.0

### ISSUE THREAD

**Issue by sdepablos** [schmittjoh/metadata#44]
A few days ago we upgraded a few packages in our SF2 project and realized that our times when from 60 ms to almost 100 ms (confirmed both by newrelic and logstash), so we started to debug which one of the upgrades was to blame. 

Finally we've found the cause on the metadata package upgrade from 1.4.2 to 1.5.0. Here's a screenshot of 500 requests with version 1.4.2 vs 500 with version 1.5.0

![jms-perf](https://f.cloud.github.com/assets/211364/2527910/05e0ab9c-b50a-11e3-9229-59a2e9ae5152.png)

Taking a look to the [differences between 1.4.2 vs 1.5.0](https://github.com/schmittjoh/metadata/compare/1.4.2...1.5.0) the only possible cause may be the pull request #36 (medatada caching improvement).  I see on the issue that a benchmark was done, but I don't know which kind of benchmark and if it was done with "real code". Could it be that the change from one call to _instanceof_ to five (two directly on _getMetadataForClass_ and three more calling _filterNullMetadata_) is causing this performance hit? It seems that as _instanceof_ uses strings comparisons, the class name length has a big impact, but this is just a guess.

**Comment by goetas** [comment]
fixed in https://github.com/schmittjoh/metadata/pull/46
