### ISSUE TITLE
consider changing chmod to @chmod

### ISSUE THREAD

**Issue by mkocztorz** [schmittjoh/metadata#50]
I have just run into trouble when using SF2 + JMS Serializer Bundle on vagrant box (windows using SMB).

The thing is that os can't use chmod on shared filesystems and attempt made here:
https://github.com/schmittjoh/metadata/blob/master/src/Metadata/Cache/FileCache.php#L45
breaks the request.

I noticed that in many places Symfony suppresses the error using @chmod so despite general rule that using @ to hide errors is bad I'd consider using it in this case. 

I made a workaround to place my cache dir outside the shared folder structure for now but this fix might be handy.

**Comment by gusdecool** [comment]
This also happen on my machine with: vagrant box with NFS on OSX.
@mkocztorz the issue that you refer to: https://github.com/symfony/symfony/issues/2125

**Comment by aequasi** [comment]
Bump. Not sure why this just started happening.

**Comment by gusdecool** [comment]
@schmittjoh in case you're agree with this change. i have created PR for it: https://github.com/schmittjoh/metadata/pull/53

**Comment by dmirkitanov** [comment]
Any luck here? This is the original discussion on the symfony repo: https://github.com/symfony/symfony/issues/8205 - they did switch to `@chmod`, so it might be a good idea to make such a change here too.

**Comment by Gemineye** [comment]
Can you please provide a new tag containing this fix?

**Comment by goetas** [comment]
was solved in https://github.com/schmittjoh/metadata/commit/e50cc464382127ff0137b7f06a5e0176b82f24db
