### ISSUE TITLE
Unexpected return value

### ISSUE THREAD

**Issue by sagikazarmark** [schmittjoh/metadata#52]
I am using this library the first time and the following issue occured: When I use the `getMetadataForClass` method I get back a hierarchy object (which probably contains all my metadata). To get the actual data I have to do the following:

``` php
$metdata = $factory->getMetadataForClass('Class');
$classMetadata = $metadata->classMetadata['Class'];
```

I think this is a bit weird and a really unfriendly behavior. Am I missing something here or this is the wy it should work. If the latter: why? Can't find any reason which beats the argument of usability.

**Comment by schmittjoh** [comment]
Make sure to implement the MergeableInterface, or extend MergeableClassMetadata if you would like to get back an instance of ClassMetadata directly, otherwise we will return the hierarchy, and you need to implement some sort of merging after that.
