### ISSUE TITLE
Update from 1.X to 2

### ISSUE THREAD

**Issue by garak** [schmittjoh/metadata#75]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | no
| BC Break report? | no
| RFC?             | yes

I can't find any update-related document in this repository, so I assume that upgrading from 1.X to 2.0 should be painless?
I'm asking because in a bundle of mine we're using 1.X version and planning to support 2.X version too, but some tests are failing.
See https://github.com/dustin10/VichUploaderBundle/pull/918

**Comment by goetas** [comment]
hmm... unfortunately did not have the time for preparing that.

Should work on it.

I can tell you that the main diff is about typehinting everywhere and removal of reflection in all metadata types except of `MethodMetadata`

**Comment by goetas** [comment]
added here migration document https://github.com/schmittjoh/metadata/blob/master/UPGRADING.md

**Comment by stephanvierkant** [comment]
From the readme: 

> The library provides three classes that you can extend to add your application specific properties, and flags: ClassMetadata, MethodMetadata, and PropertyMetadata

Correct me if I'm wrong, but it looks return types break the idea of extending those classes. See https://github.com/dustin10/VichUploaderBundle/pull/918#issuecomment-438336819. What do you think, @goetas?

**Comment by stephanvierkant** [comment]
Ping @schmittjoh

**Comment by goetas** [comment]
> Ping @schmittjoh

as per your PR, conversation about this is on 
https://github.com/schmittjoh/metadata/issues/76
