### ISSUE TITLE
Extending Metadata not possible?

### ISSUE THREAD

**Issue by stephanvierkant** [schmittjoh/metadata#76]
| Q                | A
| ---------------- | -----
| Bug report?      | **no**
| Feature request? | **no**
| BC Break report? | **yes**
| RFC?             | **no**

From the readme: 

> The library provides three classes that you can extend to add your application specific properties, and flags: ClassMetadata, MethodMetadata, and PropertyMetadata

Correct me if I'm wrong, but it looks return types break the idea of extending those classes. See https://github.com/dustin10/VichUploaderBundle/pull/918#issuecomment-438336819.

**Comment by goetas** [comment]
Well, not exactly. If you have a look at https://github.com/willdurand/Hateoas/tree/master/src/Hateoas/Configuration/Metadata it works with metadata (just migrated to metadata v2.0).

If i understand the conversation on https://github.com/dustin10/VichUploaderBundle/pull/918, IMO you should not change the signature of `*::loadMetadataFromFile`. If you do so, they are basically a different function (thus should have a different name). 

have a look at https://github.com/willdurand/Hateoas/blob/master/src/Hateoas/Configuration/Metadata/Driver/YamlDriver.php

**Comment by goetas** [comment]
> BC Break report? | yes

That's why it was released as v2.0 :smiley:

**Comment by goetas** [comment]
I guess this has been solved, since the related migration has been completed
