### ISSUE TITLE
TypeError when trying to cache anonymous class

### ISSUE THREAD

**Issue by jlekowski** [schmittjoh/metadata#79]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | yes

I understand if instances of anonymous classes are not meant to be serialized or cached, but if such is provided, an unexpected `TypeError` is thrown due to null byte issue (https://www.php.net/manual/en/security.filesystem.nullbytes.php).
```
// same with rename() function
$ php -r 'declare(strict_types=1); file_exists("file.php\0");'
PHP Fatal error:  Uncaught TypeError: file_exists() expects parameter 1 to be a valid path, string given in Command line code:1
Stack trace:
#0 Command line code(1): file_exists('file.php\x00')
#1 {main}
  thrown in Command line code on line 1
```

See the code lines:
https://github.com/schmittjoh/metadata/blob/master/src/Cache/FileCache.php#L31
https://github.com/schmittjoh/metadata/blob/master/src/Cache/FileCache.php#L64

There are ways to validate path:
- `strpos($class, "\0") !== false`
- `ctype_print($class)`
- `catch (\TypeError $e)`
- `$class->isAnonymous()`

or to fix it with `str_replace("\0", "", $class)`.

Eventually the class will not be cached using its name anyway because the name is like `class@anonymous/app/src/Controller/CoreController.php0x7f1f4ea446cf`. Also, according to the documentation https://www.php.net/manual/en/language.oop5.anonymous.php:
```
This name has to be regarded an implementation detail, which should not be relied upon.
```

## Steps required to reproduce the problem

In `Metadata\Tests\Cache\FileCacheTest` add:
```
    public function testLoadAnonymousClassMetadataFromInCache()
    {
        $cache = new FileCache($this->dir);
        $cache->load(get_class(new class {}));
    }
```
and run unit tests.

## Expected Result

* TBD (personally I'd see a custom exception, potentially silent fail)

## Actual Result

* `TypeError: file_exists() expects parameter 1 to be a valid path, string given`

**Comment by goetas** [comment]
Anonymous classes can not have cached metadata, thus are not supported by this lib.

**Comment by jlekowski** [comment]
@goetas, I understand that anonymous classes are not supported, and my intention was not a feature request to support them. I believe that like in other cases (e.g. when InvalidArgumentException or RuntimeException is thrown), this should be validated to avoid unexpected `TypeError`. Typically it is done by suppressing `@file_exists()`, but with `strict_types=1` this is not a case.

**Comment by goetas** [comment]
I see your point.

PR are welcome in this case

**Comment by jlekowski** [comment]
@goetas, I created a PR https://github.com/schmittjoh/metadata/pull/87 - anonymous classes should not result in TypeError any more and are cacheable.

**Comment by jlekowski** [comment]
@goetas, please let me know if there is a solution that would work for you here - I'd prefer to close this one instead of having it hanging.

Current behaviour with anonymous classes is that it works if no cache or `DoctrineCacheAdapter` is used. Trying to use `FileCache` or `PsrCacheAdapter` causes error (as in my [PR](https://github.com/schmittjoh/metadata/pull/87)).

A solution could be:
- do not support anonymous classes at all (exception)
- do not support caching for anonymous classes (exception or silently do not cache)
- throw an exception when trying to cache anonymous class in `FileCache` or `PsrCacheAdapter`
- analyse anonymous class so that it can be reliably cached based not on its name, but metadata
- leave it as is

**Comment by goetas** [comment]
> Current behaviour with anonymous classes is that it works if no cache or DoctrineCacheAdapter is used.

Even if "it works" it should not be used as it will fill the cache with a lot of not used metadata.

> do not support anonymous classes at all (exception)

> do not support caching for anonymous classes (exception or silently do not cache)

One of this two options sounds to be the best to me. I'm inclined to throw an exception, but i think that the best is to choose the most backward compatible option. What do you think? 

This IMO is not good as it allows defining metadata only via annotations, for who is using XML or YAML there is not way to define metadata info

> throw an exception when trying to cache anonymous class in FileCache or PsrCacheAdapter
analyse anonymous class so that it can be reliably cached based not on its name, but metadata

"reliably cached based not on its name" is hard to implement

> leave it as is

Since you are seeing it as an issue, I guess that many other people do, so it should be solved somehow

**Comment by jlekowski** [comment]
@goetas, it is your project and you have a big picture of how things need to work. I agree the most backward compatible solution would be the best here. I believe that would mean throwing an exception inside `FileCache` and `PsrCacheAdapter` - it would be more descriptive that current `TypeError`. I will create a PR.

Intentional handling of anonymous classes could be a feature in the future.

**Comment by jlekowski** [comment]
@goetas, please have a look at my PR when you have time. Feedback/Suggestions are welcomed.

**Comment by goetas** [comment]
I'm sorry if is taking so much time, but recently i'm pretty busy. Will do my best to not have this waiting too long
